# Generated by Django 4.1.3 on 2023-01-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_alter_entity_id_alter_entity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='kind',
            field=models.CharField(choices=[('person', 'person'), ('organization', 'organization'), ('evidence', 'evidence'), ('transaction', 'transaction'), ('-', '-')], default='-', max_length=15),
        ),
    ]
