# Generated by Django 4.1.3 on 2023-01-17 07:41

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0003_entity_kind'),
    ]

    operations = [
       TrigramExtension()
    ]
