# Generated by Django 4.1.3 on 2023-02-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0004_trigram'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=300)),
                ('attribute', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='entity',
            name='kind',
            field=models.CharField(choices=[('person', 'person'), ('organization', 'organization'), ('evidence', 'evidence'), ('transaction', 'transaction'), ('asset', 'asset'), ('-', '-')], default='-', max_length=15),
        ),
    ]
