# Generated by Django 4.1.3 on 2023-03-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0005_updateentity_alter_entity_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('attribute', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='entity',
            name='kind',
        ),
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='searchapp.label'),
        ),
    ]
