version: '3.3'

volumes:
    media: {}
    static: {}
    graph_db: {}
    db: {}

services: 
    db:
        container_name: ${PROJECT_NAME}-db
        image: postgres:11.3-alpine
        env_file:
            - .env
        volumes:
            - db:/var/lib/postgresql/data
            
    neo4j:
        container_name: ${PROJECT_NAME}-neo4j
        image: neo4j:4.4.15
        volumes:
            - graph_db:/data
        env_file:
            - .env
        ports:
            - '7474:7474'
            - '7473:7473'
            - '7687:7687'

    backend:
        container_name: ${PROJECT_NAME}-backend
        build: ./backend
        command: sh runserver.sh
        volumes: 
            - ./backend:/backend
            - media:/var/www/${PROJECT_NAME}/media/
            - static:/var/www/${PROJECT_NAME}/static/
        ports: 
            - 8000:8000
        env_file: 
            - .env
    
    notebook:
        container_name: ${PROJECT_NAME}-notebook
        build:
            context: backend
            dockerfile: Dockerfile.notebook
        command: sh run-notebook.sh
        volumes: 
            - ./backend:/backend
            - ./jupyter_notebook_config.json:/config/jupyter_notebook_config.json
        ports: 
            - 8888:8888
        env_file: 
            - .env
    
    frontend:
        container_name:  ${PROJECT_NAME}-frontend-vue
        build: ./frontend
        command: sh run_frontend.sh
        volumes: 
            - ./frontend:/frontend
        ports: 
            - 8080:8080
        env_file: 
            - .env