version: '3.3'

volumes:
    media: {}
    static: {}
    graph_db: {}

services: 
    db:
        container_name: ${PROJECT_NAME}-db
        image: postgres:11.3-alpine
        env_file:
            - .env
            
    neo4j:
        image: bitnami/neo4j:5.2.0
        volumes:
            - graph_db:/bitnami
        ports:
            - '7474:7474'
            - '7473:7473'
            - '7687:7687'

    backend:
        container_name: ${PROJECT_NAME}-backend
        build: ./backend
        command: sh runserver.sh
        volumes: 
            - ./backend:/backend
            - media:/var/www/${PROJECT_NAME}/media/
            - static:/var/www/${PROJECT_NAME}/static/
        ports: 
            - 8000:8000
        env_file: 
            - .env